### ISSUE TITLE
Question: no dependencies needed

### ISSUE THREAD

**Issue by adriaandotcom** [audiocogs/echoprint-codegen.js#1]
Is the only dependency `ffmpeg`? And how to run this library?

And I this repository is not maintained anymore, is there an alternative? Because https://github.com/echonest/echoprint-codegen/tree/master is also not maintained anymore.

cc @crackofdusk

**Comment by crackofdusk** [comment]
Hello @harianus,

I've kept this repository around for the sake of nostalgia. I have no plans of making it work.

There was another effort to run echoprint in a javascript engine, but using emscripten. It's in this branch: https://github.com/alastair/echoprint-codegen/tree/emscripten. As I recall, the problem, according to @alastair, was that echoprint itself is not that good at finding matches. I myself arrived at the same conclusion when I first tried the original echoprint.

My advice would be to first evaluate whether the C++ version works for you before investing time in ports. The readme at https://github.com/echonest/echoprint-codegen contains all the necessary information on how to get started.

As for alternatives, I remember this article: [Creating Shazam in Java](http://www.royvanrijn.com/blog/2010/06/creating-shazam-in-java/)

Going through it again I found:
- [How shazam works](https://laplacian.wordpress.com/2009/01/10/how-shazam-works/)
- [An Industrial-Strength Audio Search Algorithm](http://www.ee.columbia.edu/~dpwe/papers/Wang03-shazam.pdf), a paper about the algorithm in Shazam
- http://labrosa.ee.columbia.edu/~dpwe/resources/matlab/fingerprint/, a matlab implementation
- http://labrosa.ee.columbia.edu/matlab/audfprint/, a more feature complete matlab implementation by the same author
- https://github.com/dpwe/audfprint, a python implementation, by the same author.

**Comment by adriaandotcom** [comment]
> ... As I recall, the problem, according to @alastair, was that echoprint itself is not that good at finding matches ...

I just wanted to use it for [mooma.sh/api.html](http://www.mooma.sh/api.html), I tested it on my Mac and it worked quite nice, so thats why I'm still want to use it. But I want to run it from a server _(ubuntu)_ so I was looking for a other solution then for Mac.

In Ubuntu there is no `ffmeg`, `libboost1.42-dev`, `libtag1-dev`, `zlib1g-dev` anymore, so I don't now how to get that running.

Another solution I found is [doreso](http://doreso.com), here you have to upload a file instead of using fingerprint software.

[github.com/dpwe/audfprint](https://github.com/dpwe/audfprint) seems nice, maybe for when I want to run the whole recognition service myself.

Thanks for the great reply @crackofdusk

**Comment by alastair** [comment]
I wanted to try the moomash api, but haven't got around to it yet. When you tested did you use OTA recordings, or a fingerprint code from a file on disk?

Anyway, you should be able to try and play around with https://github.com/alastair/acoustiscrobbler
You'll need to compile the branch that @crackofdusk mentioned, though I think I didn't write any instructions here. I think you need to compile zlib with emcc, and then you might be able to use the Makefile.
Let me know if you have futher questions, and I could try and work out some more instructions.
